name: Bug Report
description: |
  Something is broken in Zed (exclude crashing).
type: "Bug"
body:
  - type: textarea
    attributes:
      label: Summary
      description: Describe the bug as well as provide steps to reproduce it
      value: |
        <!-- Please insert a one line summary, describing the issue here -->
        Summary:

        <!-- Include all steps necessary to reproduce from a clean Zed installation. Be verbose -->
        Steps to trigger the problem:
        1.
        2.
        3.

        Actual Behavior:

        Expected Behavior:

    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Zed Version and System Specs
      description: 'Open Zed, and in the command palette select "zed: Copy System Specs Into Clipboard"'
      placeholder: |
        Output of "zed: Copy System Specs Into Clipboard"
    validations:
      required: true
